---
- name: "Set relayhost in main.cf"
  ansible.builtin.lineinfile:
    path: "{{ postfix_config_file }}"
    regexp: "^relayhost"
    line: "relayhost = {{ postfix_relayhost }}"
    state: present
  notify: "Restart postfix"
  when: postfix_relayhost is defined

- name: "Configure SASL authentication"
  when: postfix_sasl_username is defined and postfix_sasl_password is defined and postfix_relayhost is defined
  block:
    - name: "Set SASL configuration to main.cf"
      ansible.builtin.lineinfile:
        path: "{{ postfix_config_file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^smtp_sasl_auth_enable"
          line: "smtp_sasl_auth_enable = yes"
        - regexp: "^smtp_sasl_password_maps"
          line: "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd"
        - regexp: "^smtp_sasl_security_options"
          line: "smtp_sasl_security_options = noanonymous"
        - regexp: "^smtp_tls_security_level"
          line: "smtp_tls_security_level = may"
        - regexp: "^header_size_limit"
          line: "header_size_limit = 4096000"
      notify:
        - "Restart postfix"
        - "Restart saslauthd"

    - name: "Check sasl_passwd file exists"
      ansible.builtin.stat:
        path: /etc/postfix/sasl_passwd
      register: sasl_passwd

    - name: "Create sasl_passwd file"
      ansible.builtin.file:
        path: /etc/postfix/sasl_passwd
        state: touch
        owner: root
        group: postfix
        mode: "0440"
      when: not sasl_passwd.stat.exists

    - name: "Ensure sasl_passwd has correct permissions"
      ansible.builtin.file:
        path: /etc/postfix/sasl_passwd
        state: file
        owner: root
        group: postfix
        mode: "0440"
      when: sasl_passwd.stat.exists

    - name: "Set SASL credentials in sasl_passwd"
      ansible.builtin.lineinfile:
        path: /etc/postfix/sasl_passwd
        regexp: "^{{ postfix_relayhost | ansible.builtin.regex_escape() }}"
        line: "{{ postfix_relayhost }} {{ postfix_sasl_username }}:{{ postfix_sasl_password | quote }}"
        state: present
      notify:
        - "Run Postmap sasl_passwd"
        - "Restart saslauthd"
        - "Restart postfix"

    - name: "Check sasl_passwd.db exists"
      ansible.builtin.stat:
        path: /etc/postfix/sasl_passwd.db
      register: sasl_passwd_db

    - name: "Check sasl_passwd.lmdb exists"
      ansible.builtin.stat:
        path: /etc/postfix/sasl_passwd.lmdb
      register: sasl_passwd_lmdb

    - name: "Run postmap sasl_passwd"
      ansible.builtin.command: "postmap /etc/postfix/sasl_passwd"
      notify:
        - "Restart saslauthd"
        - "Restart postfix"
      changed_when: true
      when: not sasl_passwd_db.stat.exists and not sasl_passwd_lmdb.stat.exists

    - name: "Ensure sasl_passwd.db permissions are correct"
      ansible.builtin.file:
        path: "/etc/postfix/sasl_passwd.db"
        state: file
        owner: root
        group: postfix
        mode: "0640"
      notify:
        - "Restart saslauthd"
        - "Restart postfix"
      when: sasl_passwd_db.stat.exists
